// Cross-language corpus parity: the vector in testdata/seed_vector.txt was
// generated by ../once-campfire-python's domain/workload.py seeder. The V
// seeder must reproduce it byte for byte, which is what makes the benches
// comparable across ports.
module main

import os
import workload as w

fn vector_path() string {
	return os.join_path(os.dir(os.dir(os.dir(os.dir(os.executable())))), 'campfile', 'testdata',
		'seed_vector.txt')
}

fn test_seed_vector() {
	path := 'campfile/testdata/seed_vector.txt'
	content := os.read_file(path) or { panic(err) }
	lines := content.trim_space().split('\n')
	mut cases := [][]string{}
	mut current := []string{}
	for raw in lines {
		line := raw.trim_space()
		if line.starts_with('# seed_store(') {
			if current.len > 0 {
				cases << current
			}
			current = []string{}
			continue
		}
		if line.starts_with('#') {
			continue
		}
		current << line
	}
	if current.len > 0 {
		cases << current
	}
	assert cases.len == 2
	specs := [[6, 25, 42], [8, 200, 7]]
	for ci, expected in cases {
		spec := specs[ci]
		mut s := w.seed_store(spec[0], spec[1], spec[2])
		assert s.messages.len == expected.len
		for i, line in expected {
			m := s.messages[i]
			mentions := m.mention_ids.map(it.str()).join(',')
			got := '${m.id}|${m.room_id}|${m.creator_id}|${m.created_at}|${mentions}|${m.body}'
			assert got == line
		}
	}
}
