module rails

import time

fn test_cookie_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	signed := s.sign_cookie('session_token', '"abc123"', time.Time{})!
	back := s.verify_cookie('session_token', signed, now)!
	assert back == '"abc123"'
}

fn test_cookie_rejects_wrong_name() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	signed := s.sign_cookie('session_token', '"abc123"', time.Time{})!
	if _ := s.verify_cookie('other', signed, now) {
		assert false, 'expected purpose rejection'
	} else {
		assert err.msg() == 'invalid signed or encrypted message'
	}
}

fn test_cookie_expiry() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	past := time.Time{
		year:  2020
		month: 1
		day:   1
	}
	signed := s.sign_cookie('session_token', '"abc123"', past)!
	if _ := s.verify_cookie('session_token', signed, time.now()) {
		assert false, 'expected expiry rejection'
	} else {
		assert err.msg() == 'invalid signed or encrypted message'
	}
}

fn test_encrypted_cookie_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	enc := s.encrypt_cookie('session_token', '"tok-1"', time.Time{})!
	back := s.decrypt_cookie('session_token', enc, now)!
	assert back == '"tok-1"'
}

fn test_stream_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	name := room_stream('Rooms::Open', 7)
	signed := s.sign_stream(name)
	assert s.verify_stream(signed)! == name
	kind, id := stream_room(name)!
	assert kind == 'Rooms::Open'
	assert id == 7
	assert user_rooms_stream(3).ends_with(':rooms')
}

fn test_verifier_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	v := s.app_verifier('test-verifier')
	signed := v.generate_raw('{"a":1}'.bytes(), 'test-purpose', time.Time{})!
	assert v.verify_raw(signed, 'test-purpose', now)! == '{"a":1}'
	if _ := v.verify_raw(signed, 'other', now) {
		assert false, 'expected purpose mismatch'
	} else {
		assert err.msg() == 'message purpose mismatch'
	}
}

fn test_signed_id_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	token := s.signed_id('User', 42, 'login', time.Time{})
	assert s.verify_id('User', token, 'login', now)! == 42
}

fn test_sgid_roundtrip() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.now()
	gid := 'gid://campfire/User/42'
	token := s.sgid(gid, 'login', time.Time{})
	assert s.verify_sgid(token, 'login', now)! == gid
}

fn test_escape_cookie() {
	assert escape_cookie('a b~*') == 'a+b%7E*'
	assert unescape_cookie('a+b%7E*') == 'a b~*'
	assert unescape_cookie('%zz') == '%zz'
}

fn test_go_vectors() {
	s := new_secrets('test-secret-key-base-for-campfire-v-port')!
	now := time.Time{
		year:  2026
		month: 5
		day:   1
		hour:  12
	}
	// Deterministic outputs generated by the Go port (TestZZDumpVectors).
	go_sign := 'eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltRmlZekV5TXlJPSIsImV4cCI6bnVsbCwicHVyIjoiY29va2llLnNlc3Npb25fdG9rZW4ifX0=--077d5c36bbe3081633d8170e6d175ea3ee7a7812'
	assert s.sign_cookie('session_token', '"abc123"', time.Time{})! == go_sign
	assert s.verify_cookie('session_token', go_sign, now)! == '"abc123"'
	go_stream := 'IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk53Om1lc3NhZ2VzIg==--1f0d9f37b77462ca597016d990648f9b0aa955e439a965cbb024453eec20e7f6'
	assert s.sign_stream(room_stream('Rooms::Open', 7)) == go_stream
	assert s.verify_stream(go_stream)! == room_stream('Rooms::Open', 7)
	go_verifier := 'eyJfcmFpbHMiOnsiZGF0YSI6ImhlbGxvIiwicHVyIjoidGVzdC1wdXJwb3NlIn19--4dfcb29b065af169c69f0aa6395fead2b03d4500'
	v := s.app_verifier('test-verifier')
	assert v.generate_raw('"hello"'.bytes(), 'test-purpose', time.Time{})! == go_verifier
	assert v.verify_raw(go_verifier, 'test-purpose', now)! == '"hello"'
	go_sid := 'eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6InVzZXIvbG9naW4ifX0--d31a82d94452e18e3550d75ce94227c5f01e20a034884acb3ac1e3c14a2db98b'
	assert s.signed_id('User', 42, 'login', time.Time{}) == go_sid
	assert s.verify_id('User', go_sid, 'login', now)! == 42
	go_sgid := 'eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvNDIiLCJwdXIiOiJsb2dpbiJ9fQ==--68584df2c763e89d57d2b10ae90778524d4ac241'
	assert s.sgid('gid://campfire/User/42', 'login', time.Time{}) == go_sgid
	assert s.verify_sgid(go_sgid, 'login', now)! == 'gid://campfire/User/42'
	assert canonical_json('{"b":2,"a":[1,"x<y>"]}'.bytes(), true)! == '{"b":2,"a":[1,"x\\u003cy\\u003e"]}'.bytes()
}
